import { StyleSheet } from "react-native";

export const COLORS = {
  bg: "#F9F8F6",
  ink: "#1C1C1E",
  muted: "#777773",
  green: "#4A6B5D",
  pale: "#E5EBE8",
  card: "#FFFFFF",
  line: "#E5E4E0",
  red: "#B23B3B",
  gold: "#C28E38",
  chipBg: "#F1EFEA",
};

export const splitStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.bg },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 12,
    gap: 12,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.line,
  },
  headerTitle: { flex: 1, color: COLORS.ink, fontSize: 20, fontWeight: "700" },
  headerAction: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: COLORS.pale,
  },
  headerActionText: { color: COLORS.green, fontWeight: "700", fontSize: 13 },
  content: { padding: 20, paddingBottom: 140, gap: 16 },

  card: {
    backgroundColor: COLORS.card,
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.line,
    gap: 12,
  },
  sectionTitle: { color: COLORS.ink, fontSize: 15, fontWeight: "700" },
  sectionSub: { color: COLORS.muted, fontSize: 12 },
  eyebrow: { color: COLORS.muted, fontSize: 10, letterSpacing: 1.4, fontWeight: "700" },

  amountInput: {
    color: COLORS.ink,
    fontSize: 40,
    fontWeight: "700",
    paddingVertical: 4,
    letterSpacing: -0.5,
  },
  noteInput: {
    color: COLORS.ink,
    fontSize: 15,
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: COLORS.chipBg,
    borderRadius: 12,
  },

  modeRow: { flexDirection: "row", gap: 8, backgroundColor: COLORS.chipBg, padding: 4, borderRadius: 14 },
  modePill: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: "center",
  },
  modePillActive: { backgroundColor: COLORS.card, shadowColor: "#000", shadowOpacity: 0.05, shadowRadius: 6, shadowOffset: { width: 0, height: 2 }, elevation: 2 },
  modePillText: { color: COLORS.muted, fontSize: 13, fontWeight: "600" },
  modePillTextActive: { color: COLORS.ink },

  memberRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 8,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: { color: "#FFF", fontSize: 13, fontWeight: "700" },
  memberName: { color: COLORS.ink, fontSize: 15, fontWeight: "600" },
  memberSub: { color: COLORS.muted, fontSize: 12, marginTop: 2 },
  memberOwed: { color: COLORS.ink, fontSize: 15, fontWeight: "700" },
  memberOwedMuted: { color: COLORS.muted, fontSize: 12, fontWeight: "500" },

  smallInput: {
    borderWidth: 1,
    borderColor: COLORS.line,
    backgroundColor: COLORS.bg,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    minWidth: 80,
    textAlign: "right",
    color: COLORS.ink,
    fontSize: 14,
    fontWeight: "600",
  },

  shareControls: { flexDirection: "row", alignItems: "center", gap: 6 },
  shareBtn: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.chipBg,
  },
  shareVal: { minWidth: 34, textAlign: "center", color: COLORS.ink, fontWeight: "700" },

  addMemberRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderTopWidth: 1,
    borderTopColor: COLORS.line,
    paddingTop: 12,
    marginTop: 4,
  },
  inputPill: {
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: COLORS.ink,
    fontSize: 16,
    fontWeight: "500",
    backgroundColor: "#FFFFFF",
    minHeight: 46,
  },
  iconBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.green,
  },
  removeBtn: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FEECEC",
  },

  payerBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: COLORS.pale,
    borderRadius: 6,
    marginTop: 3,
  },
  payerBadgeText: { color: COLORS.green, fontSize: 10, fontWeight: "700", letterSpacing: 0.6 },

  settlementRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: COLORS.line,
    gap: 12,
  },
  settleToggle: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: COLORS.pale,
  },
  settleToggleDone: { backgroundColor: COLORS.green },
  settleToggleText: { color: COLORS.green, fontWeight: "700", fontSize: 12 },
  settleToggleTextDone: { color: "#FFF" },

  chipsRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 8 },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: COLORS.chipBg,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  chipText: { color: COLORS.ink, fontSize: 12, fontWeight: "600" },

  ctaWrap: {
    position: "absolute",
    left: 20,
    right: 20,
    bottom: 24,
    gap: 8,
  },
  cta: {
    backgroundColor: COLORS.green,
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  ctaDisabled: { opacity: 0.5 },
  ctaText: { color: "#FFF", fontSize: 15, fontWeight: "700" },
  ctaHint: { color: COLORS.muted, fontSize: 12, textAlign: "center" },
  errorText: { color: COLORS.red, fontSize: 13, fontWeight: "600" },

  emptyBox: { alignItems: "center", padding: 32, gap: 8 },
  emptyText: { color: COLORS.muted, fontSize: 14, textAlign: "center" },

  listCard: {
    backgroundColor: COLORS.card,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.line,
    marginBottom: 10,
    gap: 6,
  },
  listRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  listAmount: { color: COLORS.ink, fontSize: 17, fontWeight: "700" },
  listPill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    fontSize: 10,
    fontWeight: "700",
    overflow: "hidden",
  },

  modalShade: { flex: 1, backgroundColor: "rgba(0,0,0,0.35)", justifyContent: "flex-end" },
  sheet: { backgroundColor: COLORS.card, borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 20, paddingBottom: 32, gap: 12, maxHeight: "80%" },
  sheetHead: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  sheetTitle: { color: COLORS.ink, fontSize: 18, fontWeight: "700" },

  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderWidth: 1.5,
    borderColor: COLORS.green,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: "#FFFFFF",
  },
  searchInput: {
    flex: 1,
    color: COLORS.ink,
    fontSize: 16,
    fontWeight: "600",
    padding: 0,
    minHeight: 22,
  },
  searchEcho: {
    color: COLORS.green,
    fontSize: 12,
    fontWeight: "600",
    paddingHorizontal: 4,
  },
});
